/* CONSULTAS */

CREATE VIEW
VI_ProAlmCan AS
SELECT KARDEX.ProCod, KARDEX.AlmCod, AlmNom, KarCan
FROM KARDEX
INNER JOIN PRODUCTO
ON PRODUCTO.ProCod = KARDEX.ProCod
INNER JOIN ALMACEN
ON ALMACEN.AlmCod = KARDEX.AlmCod;

CREATE VIEW
VI_ProEntMes AS
SELECT KARDEX_DET.ProCod, KARDEX_DET.AlmCod, AlmNom, KarDetCan, KarDetAnio, KarDetMes, KarDetDia
FROM KARDEX_DET
INNER JOIN PRODUCTO
ON PRODUCTO.ProCod = KARDEX_DET.ProCod
INNER JOIN ALMACEN
ON ALMACEN.AlmCod = KARDEX_DET.AlmCod
WHERE KarDetOpe = 1 AND KarDetEstReg = 1;

CREATE VIEW
VI_ProSalMes AS
SELECT KARDEX_DET.ProCod, KARDEX_DET.AlmCod, AlmNom, KarDetCan, KarDetAnio, KarDetMes, KarDetDia
FROM KARDEX_DET
INNER JOIN PRODUCTO
ON PRODUCTO.ProCod = KARDEX_DET.ProCod
INNER JOIN ALMACEN
ON ALMACEN.AlmCod = KARDEX_DET.AlmCod
WHERE KarDetOpe = 0 AND KarDetEstReg = 1;

/* REPORTES */

CREATE VIEW
VI_Alm AS
SELECT AlmCod, AlmNom, AlmUbi
FROM ALMACEN
WHERE AlmEstReg = 1;

CREATE VIEW
VI_Pro AS
SELECT ProCod, ProNom, UniDes
FROM PRODUCTO
INNER JOIN UNIDAD
ON PRODUCTO.UniCod = UNIDAD.UniCod
WHERE ProEstReg = 1;

CREATE VIEW
VI_KarCab AS
SELECT KARDEX.ProCod, ProNom, UniDes, KARDEX.AlmCod, AlmNom, KarCan, KarValUni
FROM KARDEX
INNER JOIN PRODUCTO
ON PRODUCTO.ProCod = KARDEX.ProCod
INNER JOIN ALMACEN
ON ALMACEN.AlmCod = KARDEX.AlmCod
INNER JOIN UNIDAD
ON UNIDAD.UniCod = PRODUCTO.UniCod
WHERE KarEstReg = 1;

CREATE VIEW
VI_KarDet AS
SELECT KarDetCod, ProCod, AlmCod, KarDetAnio, KarDetMes, KarDetDia, DocNom, KarDetDocNum, KarDetOpe, KarDetCan, KarDetValUni, KarDetValTot, KarDetSalCan, KarDetSalValUni, KarDetSalValTot, KarDetObs
FROM KARDEX_DET
INNER JOIN DOCUMENTO
ON KARDEX_DET.DocCod = DOCUMENTO.DocCod
WHERE KarDetEstReg = 1;